### ISSUE TITLE
Unable to mock response classes

### ISSUE THREAD

**Issue by whippet71** [RobinTTY/NordigenApiClient#10]
I'm currently trying to write some unit tests for a project that uses this library. I'd like to be able to mock the NordigenApiResponse<T1,T2> class, and check that my code responds to various response objects appropriately. However I can't do this as the class doesn't have an interface or public constructor/setters. 

If this class could have an interface that would be great, although I'm open to other suggestions as to how this could be achieved.

**Comment by RobinTTY** [comment]
The constructor is now public. Hadn't considered the need to mock this class since I only test with real responses right now. But makes absolute sense to be able to mock it. Didn't want to create an interface only for testing.

**Comment by whippet71** [comment]
Brilliant thank you :-)

**Comment by whippet71** [comment]
Hi Robin I have one final request (sorry!) In NordigenClient would it be possible to mark the endpoints as virtual? At the moment I am unable to mock them.

**Comment by RobinTTY** [comment]
> Hi Robin I have one final request (sorry!) In NordigenClient would it be possible to mark the endpoints as virtual? At the moment I am unable to mock them.

I was thinking about adding an interface for that class anyway for DI. That would solve your problem as well I guess?

**Comment by whippet71** [comment]
It would indeed!

**Comment by RobinTTY** [comment]
@whippet71 New interface is in v6.2.0 ;)

**Comment by whippet71** [comment]
Hi Robin sorry to be a pain - I am still having issues trying to mock the endpoints. What I would like to do is something like this:

```
nordigenClientMock = new Mock<INordigenClient>();
institutionsEndpointMock = new Mock<InstitutionsEndpoint>(nordigenClientMock.Object);
nordigenClientMock.Setup(s => s.InstitutionsEndpoint).Returns(institutionsEndpointMock.Object);
institutionsEndpointMock.Setup(expression: s => s.GetInstitution(
    It.IsAny<string>(),
    It.IsAny<CancellationToken>())).ReturnsAsync(...);

```

However this is failing, and I _think_ it's because the endpoints require a NordigenClient to be passed in their constructor (not an INordigenClient). And because NordigenClient doesn't have a default constructor, that fails... I am not actually sure what the best solution is here, any thoughts?

**Comment by whippet71** [comment]
That's great, thanks for responding so quickly

**Comment by whippet71** [comment]
Amazing, all good now - thanks again for all of your work on this, you've been a massive help
