### ISSUE TITLE
RequisitionsEndpoint.GetRequisitions Results.Result is empty

### ISSUE THREAD

**Issue by safigi** [RobinTTY/NordigenApiClient#3]
GetRequisitions does not have a good result.

var req = await client.RequisitionsEndpoint.GetRequisitions(0, 100);
foreach (var item in req.Result.Results)
{
}

if you check:
req.Resoult.Count = 3
But 
req.Result.Results = 0

I think this is a deserialization issue.

**Comment by RobinTTY** [comment]
The ```GetRequisitions```  method has the following signature:

```
await client.RequisitionsEndpoint.GetRequisitions(limit: 0, offset: 100)
```

If you switch the parameters around you will probably achieve the result you wanted, I just double checked the deserialization seems to be working. Also keep in mind that the result count will always indicate the total results across all response pages, so you might in some cases need to fetch multiple pages to get all results.

**Comment by safigi** [comment]
Good catch, thanks
