### ISSUE TITLE
Unknown fields {'payments_enabled'} in payload  (https://ob.nordigen.com/api/v2/institutions)

### ISSUE THREAD

**Issue by safigi** [RobinTTY/NordigenApiClient#4]
I think nordigen removed the "payments_enabled" in query string.

 var query = new KeyValuePair<string, string>[] {new("country", country), new("payments_enabled", paymentsEnabled.ToString())};

We give back an error:

Unknown fields {'payments_enabled'} in payload

Would you remove from the querystring?

**Comment by RobinTTY** [comment]
Thanks for reporting the issue, fixed with library version 6.0.1.

**Comment by safigi** [comment]
Thanks, working
