### ISSUE TITLE
Further CurrencyExchange issues

### ISSUE THREAD

**Issue by whippet71** [RobinTTY/NordigenApiClient#8]
Further to issue #6 it appears that the CurrencyExchange can be returned as _either_ an array _or_ a single object! Using the latest version failed as my request for account transactions included the following JSON:
`	"currencyExchange": {
		"instructedAmount": {
			"amount": "3.35",
			"currency": "EUR"
		},
		"sourceCurrency": "EUR",
		"exchangeRate": "1.1552",
		"unitCurrency": "GBP",
		"targetCurrency": "GBP"
	},`

Furthermore, it also contained an InstructedAmount section which appears to be new. I will submit a pull request later

**Comment by RobinTTY** [comment]
Oh ok, interesting API behavior ;)
Thanks for reporting, will publish a new version of this library once your PR is merged.
